AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "Gemfile"
    - "flipper-notifications.gemspec"
    - "Rakefile"
    - "bin/*"
    - "spec/rails/**/*"

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  EnforcedStyle: double_quotes
