name: Tests (Rails app)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 6 * * *" # 6 A.M.

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
          - 3.2
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Ruby version
        run: ruby -v
      - name: Install dependencies
        working-directory: spec/rails/defaults
        run: bundle install && bundle exec appraisal install
      - name: Run tests
        working-directory: spec/rails/defaults
        run: bundle exec appraisal rails test
